# 데이터 불러오기

In [3]:
import pandas as pd
import os
rating_file_path=os.getenv('HOME') + '/aiffel/recommendata_iu/data/ml-1m/ratings.dat'
ratings_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_csv(rating_file_path, sep='::', names=ratings_cols, engine='python', encoding = "ISO-8859-1")
orginal_data_size = len(ratings)
ratings.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [4]:
# 3점 이상만 남깁니다.
ratings = ratings[ratings['rating']>=3]
filtered_data_size = len(ratings)

print(f'orginal_data_size: {orginal_data_size}, filtered_data_size: {filtered_data_size}')
print(f'Ratio of Remaining Data is {filtered_data_size / orginal_data_size:.2%}')

orginal_data_size: 1000209, filtered_data_size: 836478
Ratio of Remaining Data is 83.63%

In [5]:
# rating 컬럼의 이름을 count로 바꿉니다.
ratings.rename(columns={'rating':'count'}, inplace=True)

In [6]:
ratings['count']

0          5
1          3
2          3
3          4
4          5
          ..
1000203    3
1000205    5
1000206    5
1000207    4
1000208    4
Name: count, Length: 836478, dtype: int64

In [7]:
# 영화 제목을 보기 위해 메타 데이터를 읽어옵니다.
movie_file_path=os.getenv('HOME') + '/aiffel/recommendata_iu/data/ml-1m/movies.dat'
cols = ['movie_id', 'title', 'genre'] 
movies = pd.read_csv(movie_file_path, sep='::', names=cols, engine='python', encoding='ISO-8859-1')
movies

,movie_id,title,genre
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

## 데이터 병합

In [8]:
data = pd.merge(movies,ratings, how='outer',on='movie_id')

data = pd.merge(ratings,movies)

data = data[["user_id","title","count",]]
data.sort_values("user_id")

        user_id                                   title  count
0             1  One Flew Over the Cuckoo's Nest (1975)      5
31113         1                             Antz (1998)      4
31674         1                Girl, Interrupted (1999)      4
32044         1                         Hercules (1997)      4
32415         1                          Aladdin (1992)      4
...         ...                                     ...    ...
657728     6040             Vanya on 42nd Street (1994)      4
393446     6040                          M*A*S*H (1970)      4
253075     6040                        Big Night (1996)      3
127665     6040              Shakespeare in Love (1998)      3
738957     6040                 Twin Falls Idaho (1999)      4

[836478 rows x 3 columns]

-----------------------

# 내가 좋아하는 영화 데이터 입력

## 영화 종류와 평가인원 수는?

In [9]:
print("영화 종류 : ", len(movies["title"].unique()))
print("평가 인원 : ", len(ratings["user_id"].unique()))

영화 종류 :  3883
평가 인원 :  6039

### 좋아하는 영화 검색을 위해 title, genre 소문자로 변경

In [10]:
data["title"] = data["title"].str.lower()
data

        user_id                                              title  count
0             1             one flew over the cuckoo's nest (1975)      5
1             2             one flew over the cuckoo's nest (1975)      5
2            12             one flew over the cuckoo's nest (1975)      4
3            15             one flew over the cuckoo's nest (1975)      4
4            17             one flew over the cuckoo's nest (1975)      5
...         ...                                                ...    ...
836473     5851                           one little indian (1973)      5
836474     5854                              slaughterhouse (1987)      4
836475     5854             promise, the (versprechen, das) (1994)      3
836476     5938        five wives, three secretaries and me (1998)      4
836477     5948  identification of a woman (identificazione di ...      5

[836478 rows x 3 columns]

### 영화 검색

In [11]:
# 1번 방법 : 제목 검색 / movies[movies['title'].str.contains('영화 제목')]
movies[movies['title'].str.contains('toy story')]

# 2번 방법 : 영화 랜덤 출력
import random
sampleList = random.sample(list(data["title"]), 10)
sampleList

['pulp fiction (1994)',
 'dirty dancing (1987)',
 'armageddon (1998)',
 'miracle on 34th street (1994)',
 'babe (1995)',
 'secret garden, the (1993)',
 'insider, the (1999)',
 'nurse betty (2000)',
 'peter pan (1953)',
 "boys don't cry (1999)"]

## 모델 검증을 위한 사용자 초기 정보 세팅 (내 기호에 맞춰 데이터 입력)

In [12]:
my_favorite = ["toy story (1995)","toy story 2 (1999)","truman show, the (1998)","aliens (1986)"]

my_favorite_list = pd.DataFrame({'user_id': ["wooyong"]*4, 'title': my_favorite, 'count':[5]*4})

if not data.isin({'user_id':["wooyong"]})['user_id'].any():  # user_id에 'wooyong'이라는 데이터가 없다면
    data = data.append(my_favorite_list)                           # 위에 임의로 만든 my_favorite 데이터를 추가해 줍니다. 

data.tail(10)       # 잘 추가되었는지 확인해 봅시다.

        user_id                                              title  count
836472     5717                              master ninja i (1984)      4
836473     5851                           one little indian (1973)      5
836474     5854                              slaughterhouse (1987)      4
836475     5854             promise, the (versprechen, das) (1994)      3
836476     5938        five wives, three secretaries and me (1998)      4
836477     5948  identification of a woman (identificazione di ...      5
0       wooyong                                   toy story (1995)      5
1       wooyong                                 toy story 2 (1999)      5
2       wooyong                            truman show, the (1998)      5
3       wooyong                                      aliens (1986)      5

In [13]:
data

        user_id                                              title  count
0             1             one flew over the cuckoo's nest (1975)      5
1             2             one flew over the cuckoo's nest (1975)      5
2            12             one flew over the cuckoo's nest (1975)      4
3            15             one flew over the cuckoo's nest (1975)      4
4            17             one flew over the cuckoo's nest (1975)      5
...         ...                                                ...    ...
836477     5948  identification of a woman (identificazione di ...      5
0       wooyong                                   toy story (1995)      5
1       wooyong                                 toy story 2 (1999)      5
2       wooyong                            truman show, the (1998)      5
3       wooyong                                      aliens (1986)      5

[836482 rows x 3 columns]


# User_id, 영화제목 토크나이징

In [14]:
user_unique = data['user_id'].unique()

user_to_idx = {v:k for k,v in enumerate(user_unique)}


title_unique = data['title'].unique()
title_to_idx = {v:k for k,v in enumerate(title_unique)}

print(title_to_idx["toy story (1995)"])

40

* 토이스토리2는 3883이라는 숫자를 부여받았다.

In [15]:
temp_user_data = data['user_id'].map(user_to_idx.get).dropna()
if len(temp_user_data) == len(data):   # 모든 row가 정상적으로 인덱싱되었다면
    print('user_id column indexing OK!!')
    data['user_id'] = temp_user_data   # data['user_id']을 인덱싱된 Series로 교체해 줍니다. 
else:
    print('user_id column indexing Fail!!')


temp_title_data = data['title'].map(title_to_idx.get).dropna()
if len(temp_title_data) == len(data):
    print('title column indexing OK!!')
    data['title'] = temp_title_data
else:
    print('title column indexing Fail!!')

data

user_id column indexing OK!!
title column indexing OK!!

        user_id  title  count
0             0      0      5
1             1      0      5
2             2      0      4
3             3      0      4
4             4      0      5
...         ...    ...    ...
836477     1648   3627      5
0          6039     40      5
1          6039     50      5
2          6039    385      5
3          6039    651      5

[836482 rows x 3 columns]

In [16]:
data["count"] *= (1/5)
data

        user_id  title  count
0             0      0    1.0
1             1      0    1.0
2             2      0    0.8
3             3      0    0.8
4             4      0    1.0
...         ...    ...    ...
836477     1648   3627    1.0
0          6039     40    1.0
1          6039     50    1.0
2          6039    385    1.0
3          6039    651    1.0

[836482 rows x 3 columns]

# CSR matrix로 변환

In [17]:
from scipy.sparse import csr_matrix





num_user = data['user_id'].nunique()   # 6040
num_title = data['title'].nunique()    # 3887

csr_data = csr_matrix((data["count"], (data.user_id, data.title)), shape= (num_user, num_title))
csr_data

<6040x3628 sparse matrix of type '<class 'numpy.float64'>'
	with 836482 stored elements in Compressed Sparse Row format>

In [18]:
from implicit.als import AlternatingLeastSquares
import os
import numpy as np

# implicit 라이브러리에서 권장하고 있는 부분입니다. 학습 내용과는 무관합니다.
os.environ['OPENBLAS_NUM_THREADS']='1'
os.environ['KMP_DUPLICATE_LIB_OK']='True'
os.environ['MKL_NUM_THREADS']='1'

In [19]:
# Implicit AlternatingLeastSquares 모델의 선언
als_model = AlternatingLeastSquares(factors=1000, regularization=0.01, use_gpu=False, iterations=30, dtype=np.float32)

In [20]:
# als 모델은 input으로 (item X user 꼴의 matrix를 받기 때문에 Transpose해줍니다.)
csr_data_transpose = csr_data.T
csr_data_transpose

<3628x6040 sparse matrix of type '<class 'numpy.float64'>'
	with 836482 stored elements in Compressed Sparse Column format>

In [21]:
# 모델 훈련
als_model.fit(csr_data_transpose)

  0%|          | 0/30 [00:00<?, ?it/s]

In [22]:
wooyong, toy_story2 = user_to_idx["wooyong"], title_to_idx['toy story 2 (1999)']
wooyong_vector, toy_sotry2_vector = als_model.user_factors[wooyong], als_model.item_factors[toy_story2]

print('슝=3')

슝=3

In [23]:
wooyong_vector

array([-4.18912135e-02,  5.55646606e-03,  9.22156498e-02,  6.04223683e-02,
        2.00013459e-01,  8.61355737e-02,  8.69912095e-03,  5.92524335e-02,
        4.29167412e-02, -2.76182033e-02,  8.46340731e-02, -6.66107088e-02,
       -1.51178837e-01, -8.51858482e-02, -3.47199589e-02,  1.35271728e-01,
        7.61293247e-02,  1.52314799e-02, -2.70121489e-02, -1.43137529e-01,
        7.53935948e-02, -6.31735101e-02, -7.61426315e-02,  8.96581449e-03,
        1.76085159e-02,  5.23868836e-02, -1.29359573e-01,  1.10394778e-02,
       -7.40859238e-03,  8.09728205e-02, -1.78860664e-01, -6.11130195e-03,
       -1.27969265e-01, -8.42344463e-02, -3.85021903e-02,  1.46228939e-01,
        4.08879779e-02,  5.29193096e-02,  9.55437422e-02,  1.50990725e-01,
        1.15488164e-01,  4.06403355e-02, -7.71744270e-03, -8.47998261e-02,
       -5.63782863e-02,  8.73709768e-02, -3.17583792e-02,  7.45781437e-02,
        9.62241068e-02, -9.95896570e-03, -2.06969958e-02,  6.23912625e-02,
        6.35988042e-02,  8.41714218e-02,  1.75739545e-02,  4.85434867e-02,
        7.33878240e-02, -1.25549108e-01, -1.67718958e-02,  3.30835283e-02,
        2.84637548e-02, -3.09484429e-03,  8.37194473e-02, -6.31687343e-02,
       -8.94751549e-02,  7.70107284e-02,  3.83571759e-02,  1.26305640e-01,
        2.19454750e-01,  8.62150565e-02, -1.19619630e-01,  2.40515888e-01,
       -3.23687643e-02, -1.90085217e-01, -5.19239204e-03,  5.25582070e-03,
       -1.51439965e-01, -7.42125735e-02,  8.67232680e-02,  2.10394915e-02,
       -6.71554133e-02, -3.92470099e-02, -2.70370655e-02, -7.24428073e-02,
       -4.10799161e-02,  1.27801284e-01, -3.74222025e-02,  1.73523568e-03,
        5.77210933e-02,  1.16522871e-02, -1.16468295e-01, -1.54678046e-03,
       -3.13194282e-02, -1.25505313e-01, -1.67542100e-01,  1.51859261e-02,
        2.40058843e-02, -2.53190637e-01, -3.99570912e-02, -1.18530855e-01,
       -7.04729483e-02,  1.22051224e-01,  1.93446398e-01, -4.68851365e-02,
        1.36374841e-02,  4.78571951e-02,  7.86499903e-02,  9.88136455e-02,
       -1.00332741e-02, -1.46463156e-01,  2.06976309e-02,  1.06077403e-01,
        1.96320899e-02,  7.81502426e-02, -4.16510366e-02,  1.61810011e-01,
       -1.15949005e-01, -9.68749225e-02,  5.07488362e-02,  3.14274766e-02,
       -8.01604316e-02, -2.98812948e-02, -8.33505914e-02, -8.02093931e-03,
        1.04855252e-02, -4.65836972e-02, -8.33144188e-02,  6.32332787e-02,
       -5.71136996e-02,  4.98760550e-04,  5.23481704e-03,  4.72880453e-02,
        3.38907689e-02, -8.57272148e-02,  4.01142910e-02,  7.01131374e-02,
        1.76534690e-02, -1.80824604e-02, -4.38057445e-02,  1.20238466e-02,
       -7.58957630e-03,  1.45348366e-02,  1.15054548e-02, -2.23441217e-02,
       -5.04170395e-02, -5.17400987e-02, -5.41633032e-02, -2.16650236e-02,
        2.39797439e-02,  9.83914211e-02, -2.76778135e-02,  3.99256907e-02,
       -3.80725302e-02,  7.67247006e-02,  4.21668738e-02, -4.54849899e-02,
       -1.82191327e-01, -3.69585380e-02,  2.12327950e-02,  6.09000102e-02,
        7.81596154e-02, -4.71994141e-03,  6.66553900e-02,  1.17070302e-01,
        3.35335396e-02, -2.65574548e-02, -7.19125718e-02,  8.84801373e-02,
        5.75259440e-02, -1.57747507e-01,  3.95990610e-02, -2.78882105e-02,
       -6.39700070e-02, -8.40757862e-02,  1.73302621e-01, -4.17468958e-02,
        2.57985014e-02,  5.09068370e-02,  1.37939066e-01, -4.57608514e-02,
        6.48900494e-02, -4.32206923e-03,  4.97285463e-02,  3.53251286e-02,
        1.70955390e-01,  9.21906903e-03, -6.71960413e-02,  1.29705131e-01,
        5.90396337e-02,  1.30751906e-02,  7.65542537e-02,  9.07112472e-03,
       -1.66907251e-01, -1.35190645e-02,  9.38550308e-02, -3.03911604e-02,
        3.64653580e-02,  3.57185416e-02,  1.50668696e-01,  9.82010039e-04,
       -1.46074906e-01,  3.97742726e-02,  9.31405276e-02,  4.35463674e-02,
       -2.16614217e-01, -1.32554382e-01, -7.32436925e-02,  4.60819267e-02,
       -5.78867197e-02,  3.22208442e-02,  7.52171054e-02,  8.67459644e-03,
       -7.40519539e-03, -1.93584841e-02, -6.87212124e-02,  1.22083701e-01,
       -7.68042952e-02,  1.93390131e-01, -2.10780986e-02, -1.17204234e-01,
       -9.85005498e-02, -1.22057721e-01,  1.33403182e-01,  2.19497383e-02,
        6.26963079e-02,  3.01330425e-02, -8.52722973e-02, -1.38565972e-02,
       -1.89285986e-02,  1.01942793e-01, -8.18843022e-02, -9.21368040e-03,
       -8.23087096e-02,  1.38031365e-02,  1.00454696e-01, -3.11331269e-06,
        7.51528516e-02, -7.33543858e-02, -1.20860226e-01,  6.05786815e-02,
       -8.13396499e-02,  1.25502273e-01, -2.59026438e-02,  2.50033975e-01,
       -3.88720706e-02,  5.85652962e-02,  2.51705442e-02, -9.63956565e-02,
       -8.54260251e-02, -5.04099391e-03,  4.40378822e-02, -8.13110918e-02,
       -2.30782479e-01,  9.46352854e-02,  3.28707509e-02, -8.12712125e-03,
       -1.07843965e-01,  7.26188049e-02,  1.03658222e-01, -3.14578786e-02,
        7.16510862e-02, -1.85535729e-01,  5.30685410e-02, -1.24585424e-02,
       -8.04835781e-02, -4.12840955e-02,  1.08301066e-01, -6.76046163e-02,
       -1.10275432e-01,  3.33362408e-02, -6.04181224e-03, -8.60910043e-02,
       -2.72648390e-02, -5.51060513e-02, -9.18141678e-02,  1.06617011e-01,
        2.77591515e-02,  7.16199726e-02,  7.67554417e-02,  2.25086473e-02,
       -1.32133693e-01, -9.11019929e-03, -7.65192881e-02,  5.11801951e-02,
       -1.38787061e-01, -2.21464299e-02,  1.30874598e-02,  1.64882883e-01,
        7.94341937e-02, -9.64505002e-02,  8.84925500e-02,  8.85600373e-02,
       -7.23188594e-02, -9.04923528e-02, -4.89547066e-02,  6.02691062e-02,
        1.32410228e-01, -7.74257779e-02,  7.67438412e-02, -6.92895725e-02,
       -1.28700584e-01,  1.10313118e-01, -1.44729555e-01,  9.45852920e-02,
       -1.08810514e-01,  9.85780656e-02, -3.95660065e-02,  3.14441063e-02,
        9.86983329e-02, -8.54535177e-02, -4.77481559e-02,  2.21295804e-02,
        3.77073511e-03,  7.49181062e-02,  2.92792823e-03,  3.05429585e-02,
       -2.14840565e-02,  8.55093449e-03, -6.88878372e-02, -1.65967084e-02,
        6.36650696e-02, -8.93802419e-02,  1.02199562e-01,  1.19431704e-01,
        2.30509013e-01,  2.30493881e-02,  2.05656569e-02,  2.20349990e-02,
        9.28387716e-02,  1.83101837e-02, -7.00197518e-02,  4.91950400e-02,
       -6.83940426e-02,  6.95109889e-02,  2.85555385e-02,  3.32345478e-02,
        6.08899780e-02, -3.76991183e-02, -1.66932583e-01,  4.71586324e-02,
       -4.39891480e-02, -1.25536501e-01,  9.64560360e-02,  1.29218593e-01,
        4.97578979e-02,  4.91016693e-02, -1.14181161e-01, -8.29422846e-02,
        4.98410240e-02, -3.76062281e-02, -5.20924516e-02, -3.27464305e-02,
       -5.62947989e-03,  1.09240979e-01, -2.26898603e-02, -5.37802316e-02,
        1.08679116e-01,  1.37704775e-01, -1.27832755e-01, -6.32211342e-02,
       -3.41007672e-02, -2.07478404e-02,  1.94644239e-02,  3.33678015e-02,
        4.38314974e-02, -7.88657963e-02,  7.49637187e-02,  4.98941168e-02,
        1.33967409e-02, -4.03956100e-02,  6.92812949e-02,  2.89608305e-03,
        5.92784546e-02, -3.13026942e-02,  7.25519136e-02, -1.05805270e-01,
        1.72380044e-03,  1.28542572e-01, -1.84184145e-02,  2.32805721e-02,
        2.46069953e-02,  1.38723508e-01,  1.79771967e-02, -6.69598579e-02,
       -1.05050020e-02, -1.85500775e-02,  1.68395624e-01, -1.55641347e-01,
        4.52928804e-02,  1.74054094e-02,  8.49809721e-02, -6.17131032e-02,
        4.30151820e-02, -5.60282208e-02, -8.26956555e-02,  1.78573970e-02,
        5.50419576e-02, -1.59229308e-01, -1.07480630e-01, -3.97309326e-02,
        1.19731002e-01, -5.33758365e-02, -4.19186130e-02, -1.13530770e-01,
        1.31903738e-01, -9.95085016e-02, -1.68303132e-01, -9.48459879e-02,
        1.53418720e-01,  9.24886689e-02, -8.64730105e-02, -1.44231915e-01,
        1.31520793e-01,  1.55954175e-02, -3.95497642e-02,  1.74289882e-01,
       -3.31533253e-02, -1.03212222e-01, -3.74937765e-02, -4.51113917e-02,
        7.90072754e-02, -7.07416162e-02,  5.29717701e-03,  2.16849651e-02,
       -8.48245546e-02,  1.85370240e-02,  2.00869050e-02, -8.98147300e-02,
       -1.37815356e-01,  2.18389817e-02,  1.16123587e-01, -7.52508058e-04,
        3.22680585e-02, -4.50728228e-03, -5.97495884e-02, -1.29817100e-03,
        7.97623545e-02,  3.66394818e-02,  1.60227362e-02,  3.91800441e-02,
        4.28900402e-03,  4.96936105e-02,  4.55457792e-02,  1.56550929e-01,
       -1.67538449e-02,  1.10298559e-01, -4.71872464e-02, -1.03956684e-01,
       -1.54129058e-01,  2.79122237e-02,  8.54184777e-02,  6.65955395e-02,
        2.07792193e-01,  1.37791852e-03, -1.18948102e-01,  8.53188708e-02,
       -2.98131350e-03,  1.02534413e-01,  2.19128709e-02, -7.11915195e-02,
        4.48172027e-03, -4.51551750e-02,  1.18557647e-01,  1.90719273e-02,
        7.35467998e-03,  6.62704781e-02,  2.30315831e-02, -2.31699385e-02,
       -9.43293571e-02, -2.09450927e-02,  9.05065387e-02,  7.28808809e-04,
       -6.09716494e-03,  4.59647700e-02, -1.25690447e-02, -5.43823354e-02,
       -1.00880750e-01, -1.03292763e-01,  4.26338091e-02, -6.52905554e-02,
        3.29164527e-02,  1.21784359e-01,  9.05559957e-02,  9.27863643e-02,
       -1.01186624e-02,  3.08662821e-02, -6.28885627e-02,  9.00507569e-02,
        6.01027906e-02, -2.43185032e-02,  4.67941863e-05, -5.65112196e-03,
        2.77428888e-02,  6.32056743e-02,  3.05667352e-02,  2.50549931e-02,
        1.12449154e-01, -1.35083571e-01, -2.76066959e-02, -7.87961408e-02,
       -9.46933329e-02,  6.04731515e-02, -3.34350206e-02,  1.51184097e-01,
       -1.18490875e-01,  4.31088656e-02,  7.82329515e-02, -1.72530547e-01,
        7.88338184e-02,  1.07921183e-01,  6.80677872e-03, -1.12066582e-01,
        2.58972067e-02,  2.22117603e-02,  6.30699024e-02, -3.04841138e-02,
        3.01933642e-02,  7.11007640e-02, -2.81372275e-02, -3.03203203e-02,
        5.21214046e-02, -9.99908522e-02, -5.52114882e-02, -6.02734052e-02,
       -2.76668407e-02,  1.20066755e-01, -9.24974605e-02, -2.23437566e-02,
       -2.02712361e-02, -4.77222390e-02, -1.07667677e-01, -1.56229734e-01,
        3.91147695e-02,  4.97652814e-02,  6.12613484e-02,  8.19094107e-02,
        3.88741903e-02,  8.06667730e-02,  5.02283499e-02,  1.31134400e-02,
       -1.58017993e-01, -5.89481853e-02, -7.41591379e-02, -1.18530445e-01,
       -3.28058973e-02, -1.27451777e-01, -7.89131820e-02,  4.03074548e-02,
        1.48140162e-01, -6.10109530e-02, -3.21557932e-02,  6.16046824e-02,
        1.07700787e-01, -2.59349570e-02, -7.67466277e-02, -7.92889148e-02,
        1.39422258e-02, -2.02922020e-02, -2.94888224e-02,  6.11767080e-03,
        8.30841660e-02, -4.45189923e-02, -1.16002433e-01,  1.17492028e-01,
       -5.72157279e-02,  7.86966551e-03, -4.16037999e-02,  7.73047581e-02,
       -3.63494866e-02,  1.14191379e-02,  1.00654252e-01, -3.94078530e-03,
       -1.42568409e-01,  5.71392141e-02, -2.02787742e-02, -3.00527364e-02,
       -8.65223166e-03, -7.87099898e-02, -9.77088585e-02,  1.69168890e-01,
        9.91641060e-02, -1.68499257e-02,  3.92994769e-02,  5.97144999e-02,
       -1.02743350e-01, -7.56214559e-02,  7.52694234e-02, -5.09903242e-04,
       -6.42617866e-02, -6.46320060e-02, -7.69268274e-02, -6.44391403e-02,
        4.30958718e-02,  1.69069797e-01,  4.55772169e-02, -1.63975090e-01,
       -1.02137998e-01, -4.80074026e-02, -8.56833830e-02,  8.84370040e-03,
       -1.52843133e-01, -4.92277369e-02,  8.42251852e-02, -9.58838910e-02,
       -1.82489734e-02, -5.07775582e-02, -5.27093261e-02, -5.25817610e-02,
       -1.54122040e-01, -1.63806349e-01,  3.24428603e-02, -4.41601649e-02,
        7.81631395e-02,  1.15492299e-01,  6.06432557e-02, -6.09600134e-02,
        3.83533612e-02, -6.85532838e-02,  4.86311652e-02,  1.57251716e-01,
       -3.07275932e-02, -1.25742983e-02,  1.01477325e-01, -4.27560695e-02,
       -1.38601825e-01,  1.02399491e-01, -3.35229822e-02, -7.83767626e-02,
       -2.59211082e-02,  1.25908284e-02, -7.41564333e-02,  4.16139700e-02,
        1.55260101e-01,  5.28092161e-02,  1.25465944e-01, -9.41245928e-02,
        2.59875152e-02, -2.00900078e-01,  1.38354078e-02,  5.27507812e-02,
        5.79912914e-03, -6.97172582e-02, -8.26132223e-02, -4.73327897e-02,
       -1.76091120e-01, -3.53486696e-03, -1.47345454e-01,  3.14995609e-02,
       -2.93521024e-02,  1.10934384e-01, -6.32635951e-02,  1.51709169e-01,
       -1.29684776e-01, -9.95176658e-02, -7.85585567e-02, -9.40303411e-03,
        5.96040003e-02, -2.15276908e-02,  2.16051295e-01, -6.39689267e-02,
        1.02689695e-02, -1.15007855e-01, -2.70159449e-02,  1.64728798e-02,
        1.80188697e-02, -1.17606990e-01, -5.35957841e-03,  6.64533600e-02,
        1.63300201e-01, -2.80981828e-02, -5.51374890e-02, -4.93025333e-02,
       -9.96839702e-02,  3.01778261e-02,  1.13350987e-01,  2.42599454e-02,
       -9.32261869e-02,  3.44151352e-03,  8.69373679e-02, -3.02662365e-02,
       -2.94903666e-03, -8.02950263e-02,  7.99388662e-02, -1.06487714e-01,
        1.70259792e-02,  2.05865409e-02,  9.57724452e-02, -2.01445654e-01,
       -6.90343529e-02, -6.21475168e-02,  1.04736006e-02, -4.07984816e-02,
       -4.19789515e-02, -4.37040478e-02, -2.44958904e-02, -9.13491622e-02,
        4.19826023e-02, -6.24483675e-02,  1.53430551e-01,  1.22902915e-01,
       -8.33539739e-02,  1.09293208e-01, -2.69996021e-02,  1.52524456e-01,
       -1.11839838e-01,  9.33211967e-02, -9.07734260e-02,  1.43426448e-01,
       -5.94596714e-02, -1.70662031e-01,  2.21124990e-03, -5.98842371e-03,
       -6.80748969e-02,  3.25727351e-02, -1.59307718e-02,  4.34982497e-03,
       -1.54242679e-01, -7.23981336e-02, -1.34322599e-01, -1.43863028e-02,
       -7.46699497e-02, -9.05507281e-02, -2.77322419e-02,  1.81090117e-01,
        7.65444636e-02,  2.14238875e-02, -2.10590661e-01, -1.18708359e-02,
       -1.13352537e-01,  2.15038836e-01, -3.91321778e-02,  5.39333709e-02,
       -7.26337880e-02,  1.46098910e-02, -7.09593296e-02,  9.78722200e-02,
       -8.35484788e-02,  1.25251114e-01,  2.57329028e-02,  4.74184286e-04,
       -3.25497729e-03,  1.81102782e-01,  6.80863410e-02,  5.91317825e-02,
       -6.88025951e-02, -5.57583347e-02,  3.48823960e-04,  3.44438776e-02,
        1.08386092e-01, -1.22364327e-01,  8.03172961e-02, -1.66347519e-01,
       -1.19082302e-01,  1.17305173e-02,  4.81038056e-02, -5.97613193e-02,
        2.58917660e-01,  9.11284089e-02,  8.85953009e-03, -5.88834509e-02,
       -9.11978185e-02,  4.48802225e-02,  1.67651907e-01, -3.94875072e-02,
        2.60528982e-01,  7.54564777e-02,  4.27674577e-02, -1.47037834e-01,
       -7.29622543e-02, -5.18637039e-02, -1.23139352e-01,  1.07572004e-01,
       -4.46161218e-02,  5.38198166e-02, -1.41618520e-01, -1.21268325e-01,
        1.01771848e-02,  2.72796713e-02, -5.11449911e-02,  4.36233617e-02,
       -1.09776691e-01, -1.68333780e-02, -3.00203133e-02, -6.20706789e-02,
        1.45961866e-02, -2.79413629e-02, -5.13459556e-02, -9.70922690e-03,
        8.09398815e-02,  1.11365981e-01,  3.09389737e-03,  6.39245436e-02,
       -5.33636734e-02, -5.12351356e-02,  2.54371557e-02, -5.03026396e-02,
        1.32692903e-01,  1.49984583e-02, -2.76514562e-03,  1.34744952e-02,
        1.42612740e-01, -1.52417704e-01, -1.32587373e-01, -6.54395670e-02,
       -7.75834024e-02, -5.79878278e-02,  9.35569778e-02,  1.40698358e-01,
        1.23321511e-01, -9.61787552e-02, -8.75644311e-02, -1.18890010e-01,
        1.16854049e-01, -4.37353142e-02,  7.09215850e-02, -4.22971174e-02,
        6.09195977e-02, -1.58525966e-02,  7.51827881e-02, -1.26249596e-01,
        1.46943077e-01, -7.15456158e-02,  2.36226581e-02,  5.77867515e-02,
       -1.34118898e-02, -1.01389423e-01, -3.42410021e-02,  5.68021554e-03,
        5.29718623e-02,  9.87101123e-02, -3.38303037e-02, -9.02012587e-02,
       -8.16990715e-03, -7.92860761e-02,  1.71776399e-01, -5.52376080e-03,
        3.65001708e-02,  7.49260262e-02,  3.08386069e-02, -1.32283624e-02,
        9.68916491e-02, -4.71075214e-02,  1.00301005e-01,  4.24190760e-02,
        5.67183197e-02,  3.40615399e-02, -2.19267145e-01, -9.86730028e-03,
       -2.66547892e-02, -3.07088671e-03, -8.29797238e-02,  4.27053422e-02,
       -4.97882301e-03, -1.53275291e-02,  1.37575027e-02, -5.44803729e-03,
        3.75615545e-02, -1.56693533e-01,  8.20746720e-02,  9.45877226e-04,
        9.85615626e-02,  5.63966483e-03, -1.00194544e-01, -1.27294540e-01,
        6.62501827e-02,  1.92569960e-02, -9.92190912e-02,  8.37213397e-02,
       -4.61568013e-02, -1.74652427e-01,  8.20397511e-02, -1.21383995e-01,
       -4.41725403e-02,  1.50820643e-01,  2.61811297e-02, -3.83709325e-03,
        1.05059445e-02,  1.35466948e-01, -1.12582408e-01, -4.93319854e-02,
       -4.80607264e-02, -4.03621569e-02,  4.98926900e-02, -4.60562967e-02,
       -5.46290213e-03,  9.14666280e-02,  1.00411028e-01, -3.73160839e-02,
       -1.13906339e-01,  1.64251953e-01,  3.00689335e-05,  6.48956671e-02,
       -7.57861137e-02, -1.39951222e-02, -9.10296515e-02,  1.29519001e-01,
       -6.58266768e-02,  3.71938720e-02,  1.76489949e-01,  8.23039636e-02,
       -9.07872617e-02, -2.82018557e-02,  9.50765461e-02, -1.90559238e-01,
        3.00266258e-02, -6.21465221e-02, -1.56770125e-02,  8.27624872e-02,
        7.97344558e-03, -6.72919750e-02, -1.77804202e-01,  1.26558840e-01,
       -5.19318730e-02,  8.81650671e-02,  5.41325808e-02,  8.83958042e-02,
       -2.26536393e-03,  3.47310826e-02, -1.94441788e-02,  1.40569940e-01,
        1.21790819e-01,  1.07863933e-01,  4.38230932e-02, -1.87779590e-01,
        5.05752377e-02,  2.92135943e-02,  1.95564739e-02, -7.79390559e-02,
        1.01124033e-01,  7.32733533e-02, -1.12193048e-01,  3.16453613e-02,
        7.74169574e-03, -4.42104749e-02,  6.79443851e-02,  8.63972232e-02,
       -1.10966481e-01,  2.28693520e-04, -1.84621215e-02, -1.67364314e-01,
        5.17012319e-03,  4.20768596e-02,  1.43972561e-01,  4.44998555e-02,
        6.59745857e-02, -6.73210695e-02,  6.40337765e-02, -1.87753916e-01,
       -9.31483135e-02,  3.80169339e-02, -9.95177217e-03,  2.77318414e-02,
       -6.53413534e-02,  1.05454214e-01, -6.49515120e-03,  1.54404212e-02,
        9.49024595e-03, -5.34188002e-03,  2.82712895e-02, -2.53744349e-02,
        1.09602086e-01,  2.76490184e-03, -2.26895120e-02, -8.44637528e-02,
       -4.53628004e-02,  1.24971464e-01, -3.78444139e-03, -9.14919470e-03,
       -1.07970908e-02, -3.96375470e-02, -8.45382214e-02, -2.62010321e-02,
        1.86971858e-01, -2.94376491e-03,  5.01040630e-02, -3.53999063e-02,
        1.14535661e-02,  1.05945040e-02, -8.36284459e-02,  7.76614323e-02,
        1.40157148e-01,  1.11139193e-01, -4.55454923e-02,  1.11035310e-01,
        1.24148019e-02,  4.49741296e-02,  5.60614988e-02, -1.60381962e-02,
       -2.79717590e-03, -3.90846021e-02, -6.44164458e-02,  1.73973273e-02,
        6.18152916e-02,  2.24508196e-02, -2.10587889e-01,  7.08921673e-03,
        9.22429040e-02,  1.13532804e-01,  7.64693469e-02, -1.33090436e-01],
      dtype=float32)

In [24]:
toy_sotry2_vector

array([-1.23765776e-02,  3.81259322e-02,  3.85458060e-02,  2.49334108e-02,
        3.01065072e-02,  4.29433919e-02,  6.13730634e-03,  1.17951864e-02,
       -1.29598882e-02,  8.83598253e-03,  8.01778305e-03, -1.57687571e-02,
       -1.14244083e-02, -1.15042673e-02, -3.63702327e-02,  6.41507879e-02,
        1.83773749e-02,  3.69887762e-02,  4.54845838e-02, -2.98144612e-02,
        4.96622026e-02, -3.14281285e-02,  3.02458312e-02, -1.99681669e-02,
        3.42683233e-02,  2.92183310e-02, -2.22831927e-02, -8.01656302e-03,
       -8.65120499e-04,  5.38711734e-02, -1.86679419e-02,  6.00914052e-03,
       -6.99203927e-03, -1.64639670e-02, -9.96585190e-03,  5.61745241e-02,
        4.35943604e-02, -2.25567929e-02,  3.30814384e-02,  6.68191984e-02,
       -2.32137311e-02,  3.55173349e-02,  6.23424351e-02, -1.89306680e-02,
       -3.68604213e-02,  3.22782472e-02, -1.42511930e-02,  7.42624374e-03,
        4.50452743e-03,  1.59334410e-02,  8.00636690e-03,  1.94630120e-02,
        1.64373759e-02, -3.60925160e-02, -1.93898864e-02, -1.44025078e-02,
        1.78923123e-02, -2.74919476e-02, -2.10572174e-03,  2.92286668e-02,
        3.84868570e-02, -2.29478329e-02, -6.30103284e-03,  2.56924871e-02,
       -1.27495825e-02, -4.24485793e-03,  4.31929044e-02,  3.02429162e-02,
       -1.55852232e-02,  4.29113396e-02, -1.85127258e-02,  3.89077552e-02,
       -2.48783156e-02, -3.24451774e-02, -2.63185543e-03,  9.37189534e-03,
       -8.07291828e-03, -8.11140984e-03,  7.06665160e-04,  3.35762091e-02,
       -2.18642037e-02, -1.52848708e-02, -3.66999097e-02, -3.83502878e-02,
       -5.67745492e-02,  8.51903949e-03, -3.11026983e-02, -5.01018902e-03,
        1.33288605e-03, -3.23383100e-02, -3.26314680e-02,  2.97347642e-03,
        3.43625173e-02,  1.30455324e-03,  1.35098947e-02,  2.02774126e-02,
        5.25839510e-04, -1.71993002e-02, -1.59951486e-02,  1.19715529e-02,
       -1.50128985e-02,  2.56622247e-02,  6.16787821e-02, -1.02574145e-02,
       -1.41360229e-02,  5.03689647e-02,  2.12142393e-02, -7.79872574e-03,
       -1.90266911e-02, -1.51695544e-02,  4.22117449e-02,  4.42846306e-02,
       -2.08100881e-02,  1.64878722e-02, -3.60402167e-02,  5.17414249e-02,
       -2.96591297e-02,  1.60628594e-02,  3.28401066e-02,  3.18451300e-02,
       -3.08273472e-02, -1.98497740e-03, -4.75846827e-02, -1.63769163e-02,
        5.82990469e-03, -3.71844582e-02,  6.77936245e-03,  3.74044254e-02,
       -1.32292490e-02, -2.98038498e-02,  2.16053855e-02,  5.88081814e-02,
       -1.21745104e-02, -3.26364301e-02, -3.88717582e-03, -9.83377453e-04,
        1.06905261e-02,  1.80168767e-02,  2.34987754e-02,  3.75670306e-02,
        6.65751146e-03,  3.53118069e-02, -7.01162964e-03, -2.03634519e-03,
       -2.43535526e-02, -2.06739455e-02,  3.95006500e-02, -1.65740978e-02,
       -1.10498061e-02,  1.63373351e-02,  4.16449830e-02,  2.43256707e-02,
        1.01848785e-02,  3.62340510e-02,  3.15493979e-02,  2.66227368e-02,
       -2.14996748e-02,  1.27224624e-02,  3.23276743e-02,  2.21358463e-02,
        1.10494466e-02,  4.38872129e-02, -8.96405056e-03,  2.12617461e-02,
        3.65934595e-02,  3.53859328e-02, -5.33483457e-03,  3.82942408e-02,
       -4.64357762e-03, -3.79550233e-02,  3.18074487e-02,  2.16186773e-02,
       -2.30716285e-03,  2.75656655e-02,  4.74334620e-02,  1.81441735e-02,
        1.38167357e-02,  1.62371770e-02,  4.22070064e-02,  9.75279696e-03,
       -3.77969630e-02,  9.27811116e-03,  2.98348088e-02,  2.21990980e-02,
        1.53153073e-02,  2.63120718e-02,  3.80603485e-02,  3.58053334e-02,
        3.96350399e-03, -1.90653950e-02,  3.21116410e-02, -3.22145522e-02,
       -5.61492965e-02,  2.13734470e-02,  2.28190422e-02, -2.99538635e-02,
        3.52171087e-03, -2.84361485e-02, -2.29729749e-02,  4.53409441e-02,
       -1.57346632e-02,  5.23599610e-02, -1.15952333e-02, -3.35033722e-02,
       -5.13105243e-02, -2.16312036e-02,  9.22067370e-03,  1.85042135e-02,
       -3.91619802e-02,  6.03113091e-04,  6.34334534e-02, -2.21967362e-02,
        1.71725228e-02, -2.01221053e-02, -3.58531252e-02,  8.53745732e-03,
       -1.57661196e-02,  4.56046239e-02,  4.47014309e-02, -1.58529151e-02,
       -2.52312627e-02,  2.60283239e-02,  2.12606303e-02,  2.23142095e-02,
        3.00208200e-02,  1.90679822e-02, -2.39014272e-02,  1.86757911e-02,
        1.36790210e-02,  2.45321319e-02, -2.97664721e-02, -2.95781810e-02,
        4.00226889e-03, -8.88675638e-03,  3.41697708e-02,  2.47145630e-02,
        4.35276143e-02, -1.16247684e-02,  6.11180393e-03, -3.84994410e-03,
        1.44739458e-02,  3.42325233e-02, -3.35246809e-02,  6.19731694e-02,
        3.17550823e-02, -1.06450880e-03, -2.47377418e-02, -2.97352035e-05,
        3.08009610e-03, -1.14626307e-02, -2.29307767e-02, -5.57631161e-03,
       -2.10083532e-03,  2.78732665e-02,  4.54186313e-02, -1.06848762e-04,
       -2.11167615e-02,  1.40958158e-02,  1.71191599e-02, -2.60766651e-02,
       -2.30062567e-02, -3.36029604e-02, -2.85229683e-02, -3.16847824e-02,
        1.35739204e-02, -1.19848819e-02,  5.68204967e-04,  1.86861884e-02,
       -3.55565511e-02,  1.78632811e-02, -1.91035308e-02,  6.03982760e-03,
       -1.72918122e-02, -1.83347799e-02,  1.04121573e-03,  6.37705065e-03,
       -5.90505265e-03, -1.64270513e-02, -1.38390502e-02,  6.27185218e-03,
       -1.32820215e-02, -1.51161822e-02, -2.39302628e-02,  3.72357704e-02,
       -2.69959886e-02,  1.59968678e-02,  1.81430373e-02,  4.42311279e-02,
       -2.38856673e-02, -1.93474647e-02, -2.54814588e-02, -3.09410803e-02,
       -1.51244700e-02, -1.50209554e-02, -5.68927173e-03, -3.01011298e-02,
        2.02070903e-02,  3.20090353e-02,  3.00997915e-03,  4.44784425e-02,
       -3.76241431e-02, -4.05169558e-03,  6.73469715e-03,  9.25772917e-03,
       -1.69870239e-02,  3.30588706e-02,  2.30736677e-02,  2.40575671e-02,
       -3.75229702e-03, -4.27752919e-03, -3.49315405e-02,  1.48717640e-02,
        1.25113800e-02, -1.26288626e-02, -9.75688826e-03,  3.70973758e-02,
        3.01252790e-02,  3.34452689e-02,  2.71975100e-02,  2.41906010e-02,
        1.65318456e-02, -1.58026051e-02, -5.90297813e-03,  4.61375564e-02,
        3.29068191e-02,  2.01523528e-02, -3.14516723e-02,  1.64727122e-02,
        4.51655276e-02,  3.53575945e-02, -9.38307121e-03,  1.32533787e-02,
        1.93289649e-02,  4.69433442e-02, -2.30637211e-02, -1.60151403e-02,
       -3.59189603e-03,  3.65878083e-02, -3.12970430e-02,  4.63324934e-02,
        3.67915467e-03, -1.54349422e-02,  3.29832360e-02,  5.19267544e-02,
       -1.22898631e-02, -9.18169133e-03, -7.31424009e-03,  2.70504169e-02,
       -1.62436906e-02, -1.03745516e-02, -2.26564594e-02, -4.57662856e-03,
       -5.17649064e-03,  6.12259582e-02, -1.34276310e-02, -5.13258390e-02,
        2.73890328e-02,  3.94758955e-02, -1.73600353e-02,  4.24815429e-04,
       -1.04834493e-02, -4.60800249e-03,  2.91640740e-02,  2.26573776e-02,
       -2.60745250e-02, -3.02092973e-02,  1.67446351e-03, -2.09850017e-02,
        1.10415565e-02, -3.75190913e-03,  2.18146034e-02, -1.16703026e-02,
        8.17759242e-03, -2.00140961e-02, -8.51700827e-03, -3.91874798e-02,
        3.25836167e-02,  6.72646463e-02, -7.00313784e-03,  2.97907796e-02,
       -3.00187487e-02,  4.14076000e-02,  1.12494025e-02, -2.61900071e-02,
       -1.24488957e-02,  2.88865697e-02,  6.15865551e-02, -2.19546873e-02,
       -7.55978283e-04,  4.61308169e-04,  3.77251580e-02,  1.71810556e-02,
       -2.70840358e-02,  3.72803807e-02, -4.20299359e-03, -2.35569365e-02,
        1.34221674e-03,  6.70391461e-03,  9.56268609e-03,  4.29207496e-02,
        3.98523323e-02, -1.07422881e-02,  1.94613039e-02, -2.70767473e-02,
       -1.51589895e-02, -2.51327138e-02, -3.13021541e-02,  1.45796044e-02,
        2.47683059e-02,  2.06388682e-02, -4.62986566e-02,  2.81310044e-02,
        3.85627449e-02,  2.89947074e-02, -2.34600771e-02,  2.38516629e-02,
        2.77376547e-03, -9.24512278e-03, -1.81408338e-02,  5.31158912e-05,
       -8.18987470e-03, -2.37324089e-02,  3.92007120e-02, -1.15437841e-03,
        4.90922481e-03,  2.38285773e-02, -1.70118138e-02, -6.52346155e-03,
       -3.45508605e-02,  3.75404954e-02,  4.70175743e-02,  4.30925600e-02,
        2.42346693e-02, -1.04587711e-02,  2.45209001e-02, -3.12102176e-02,
        2.51775663e-02,  1.41126355e-02,  3.77670228e-02,  3.53644490e-02,
       -5.79262571e-03, -3.04388767e-03, -2.19114758e-02,  2.87187397e-02,
        1.38770891e-02,  4.09188457e-02,  2.76255812e-02,  2.62681600e-02,
       -9.74603370e-03,  4.15921696e-02,  1.75164361e-02,  2.72686686e-02,
        3.50287110e-02, -1.33748632e-02,  3.53877358e-02,  1.58609059e-02,
       -2.04739664e-02,  1.26959728e-02, -1.62077714e-02, -4.33208374e-03,
        2.04293411e-02,  1.06153926e-02, -1.14217056e-02, -8.95241927e-03,
        2.95412093e-02,  4.13871668e-02,  1.75938997e-02, -8.06256291e-03,
        1.84039082e-02, -1.66247110e-03,  6.46476215e-03, -2.52691451e-02,
        3.25953588e-02,  3.29236984e-02,  2.60254536e-02, -4.77045700e-02,
       -1.85171328e-02, -5.85135259e-03,  8.40156991e-03, -1.35512920e-02,
       -1.52405510e-02,  3.16869132e-02,  4.43926174e-03,  2.56613083e-02,
        1.19437122e-04,  2.19348241e-02, -2.21896805e-02,  2.06950121e-02,
        3.49911340e-02, -2.72741523e-02,  1.09100323e-02,  1.80431809e-02,
        4.41796556e-02,  2.07968578e-02,  2.46023368e-02, -2.87551386e-03,
        2.66269986e-02, -4.44628522e-02, -4.26215725e-03,  8.90468992e-03,
        2.42903344e-02, -3.36547419e-02,  1.07964803e-03,  1.67454407e-02,
       -1.47253862e-02,  3.41096111e-02, -2.10489016e-02, -4.31544036e-02,
       -4.63916874e-03,  1.15680406e-02,  4.48686890e-02, -5.57876285e-03,
       -2.73786653e-02,  3.87842841e-02,  1.53869139e-02,  2.73975767e-02,
       -1.71740185e-02, -7.59983808e-03,  2.91468836e-02,  1.61894318e-02,
       -3.22386739e-03, -1.44121731e-02, -3.62762474e-02, -1.49526438e-02,
        2.63931174e-02,  2.37823445e-02, -2.40941718e-02, -3.10623762e-03,
       -3.72778364e-02, -3.90175469e-02, -2.38938984e-02, -4.27096821e-02,
       -1.20953452e-02,  2.93828733e-02,  2.78606284e-02,  2.92681530e-02,
       -1.31251803e-02, -1.79347154e-02,  2.25951429e-02,  1.64598022e-02,
       -1.41061079e-02, -8.53712671e-03, -4.18143123e-02, -2.29509417e-02,
        2.93488968e-02,  5.23280445e-03, -1.94664709e-02, -8.45724810e-03,
        4.13062200e-02, -2.52498686e-02,  1.17563009e-02,  4.30511422e-02,
        4.11206260e-02, -2.77070478e-02, -1.72664486e-02, -1.77825447e-02,
       -3.17368098e-03,  4.48432527e-02, -8.12035403e-04,  3.25141139e-02,
       -3.35676558e-02,  2.61596628e-02, -2.87032742e-02, -2.02054381e-02,
        2.31899116e-02, -2.29265317e-02,  5.92385568e-02,  4.93310168e-02,
       -1.56970676e-02,  1.35720363e-02,  3.52130197e-02,  2.97763553e-02,
       -2.28788331e-02, -2.17081513e-03,  1.56001584e-03,  3.61757837e-02,
        2.23334562e-02, -1.87031925e-02, -3.22488770e-02,  2.65989639e-02,
        5.04462570e-02, -2.66017821e-02,  3.46859246e-02, -8.79362132e-03,
       -1.77495461e-02,  1.59239136e-02, -1.01407031e-02, -7.23567232e-03,
       -2.39037778e-02,  1.72929361e-03, -6.51053991e-03, -1.72686633e-02,
       -6.87786099e-03, -1.37513336e-02,  1.79794407e-03,  1.74747575e-02,
       -1.22182174e-02, -3.26267764e-04,  1.99603792e-02, -9.88922184e-05,
       -2.84701437e-02,  2.73804683e-02, -1.39906891e-02,  1.63626783e-02,
        3.16041112e-02, -3.06846816e-02,  4.57965136e-02,  5.22769801e-03,
       -4.57078665e-02, -2.58636475e-02,  2.75829118e-02, -3.25401314e-02,
        7.77781382e-03,  3.60281498e-04, -2.01254301e-02, -2.60723643e-02,
        3.61638796e-03, -1.48501778e-02, -5.33305435e-03,  4.04591719e-03,
       -4.00195196e-02,  1.44432113e-02,  1.65556036e-02, -2.30605844e-02,
        4.03709263e-02, -1.86162908e-02, -2.66961120e-02,  2.78049409e-02,
       -4.18679565e-02, -2.89711598e-02, -2.68353638e-03,  1.01297228e-02,
        3.36997374e-03,  1.48676988e-02,  2.03142944e-03, -2.93526556e-02,
        5.38591854e-02, -3.96313593e-02,  4.85661672e-03, -2.43848544e-02,
        1.09532695e-04, -6.31628733e-04, -1.05488794e-02, -2.20605582e-02,
       -2.73956172e-02, -5.34261996e-03, -2.69357823e-02,  5.82722574e-02,
        7.62678543e-03,  1.73674487e-02, -1.17903696e-02,  3.83081138e-02,
       -5.39857149e-03, -3.60295782e-03,  3.26145031e-02,  2.14010235e-02,
        4.42032032e-02, -8.06621648e-03,  5.40477075e-02,  4.79153655e-02,
        3.34485876e-03, -3.76958735e-02, -4.77498770e-03, -2.18614154e-02,
        3.60898525e-02, -2.03656424e-02,  3.88586521e-02,  1.24673545e-02,
        6.33850053e-04,  2.17044763e-02,  1.08789347e-04, -7.33580021e-03,
       -2.41351668e-02,  2.67233700e-02,  3.59627567e-02,  4.86195739e-03,
       -1.01254629e-02,  2.15694513e-02,  1.32302502e-02,  8.01147660e-04,
        6.70936182e-02, -2.48640049e-02,  1.80776918e-03, -2.14833114e-02,
        7.85363372e-03, -1.21117779e-03,  3.52826044e-02, -4.35706228e-02,
        2.94840820e-02, -1.11066666e-03,  3.88921648e-02,  3.22312186e-03,
       -2.24678125e-02,  2.65792534e-02, -6.66116178e-03, -5.32135461e-03,
       -1.95344873e-02, -4.04399373e-02, -3.98622127e-03, -9.07903723e-03,
       -2.31727269e-02,  7.24158017e-03, -5.47494702e-02,  4.50185016e-02,
       -3.27875279e-02, -1.89103989e-03,  2.99371891e-02, -1.63421184e-02,
       -3.50789330e-03,  6.21992303e-03,  2.30831504e-02,  1.50417527e-02,
        2.22085719e-03,  2.72838250e-02, -3.63019146e-02,  2.72371639e-02,
       -1.12924026e-02,  1.54959271e-02, -4.17515524e-02, -1.15554817e-02,
       -1.25763221e-02, -2.73596495e-02, -2.86659785e-02,  2.24969834e-02,
       -9.71819367e-03,  6.01474894e-03, -1.71213131e-02,  1.22693582e-02,
       -1.10775018e-02,  4.87296991e-02,  1.66915283e-02,  2.30326634e-02,
        3.53797115e-02,  2.60938276e-02,  5.28757982e-02,  2.39539263e-03,
       -1.85419004e-02,  1.65069085e-02, -2.03155447e-02, -1.10852846e-03,
        3.36105190e-02, -2.74981949e-02, -2.39463337e-02, -4.30034415e-04,
       -2.88834013e-02,  6.16162131e-03, -4.38837111e-02, -2.50248872e-02,
        1.06749833e-02,  2.36444478e-03, -1.17923412e-02, -1.66971870e-02,
       -4.14427295e-02, -2.40485519e-02,  3.28643993e-02, -1.46112815e-02,
        3.64549980e-02, -8.62307660e-03,  9.29316320e-03, -1.21124554e-03,
        1.24264257e-02,  5.80312572e-02,  4.05085422e-02, -1.86739117e-02,
        4.82322462e-02, -1.58669297e-02,  3.71158533e-02, -8.52468889e-04,
        9.63336136e-03, -1.02597885e-02, -2.67503541e-02,  4.13548872e-02,
        4.36456082e-03,  1.69351064e-02,  1.12434560e-02, -3.66428234e-02,
        3.97064127e-02,  9.80719808e-04,  4.75309268e-02,  5.41155133e-03,
       -7.60742580e-04, -1.62021201e-02,  2.32462008e-02,  2.63717081e-02,
        5.50306551e-02, -6.06646948e-03,  2.90445448e-03,  3.47613059e-02,
        4.22068946e-02,  3.17060240e-02,  4.51202989e-02,  5.19895442e-02,
       -2.71560531e-02, -2.49274801e-02, -4.03558044e-03, -3.86934504e-02,
        4.10470665e-02, -8.18848028e-04, -5.24793332e-03, -1.31729972e-02,
        2.94428300e-02, -4.78315093e-02, -7.40487454e-03,  8.38634092e-03,
        3.18271033e-02, -2.35961676e-02, -8.24238057e-04,  4.43662656e-03,
        9.60102584e-03,  3.73080745e-02, -1.71489380e-02, -1.44014424e-02,
        2.83205267e-02, -1.59510486e-02,  5.36085479e-02, -4.36120987e-04,
        2.32221335e-02, -2.59397961e-02, -2.80839088e-03,  7.62906112e-03,
        3.36988345e-02, -2.34078113e-02, -1.00135487e-02,  4.03358862e-02,
       -2.81192251e-02,  2.02868190e-02,  4.75208275e-02,  2.36383546e-02,
        2.15715673e-02,  8.81390739e-03, -1.37328869e-03,  3.82245444e-02,
       -1.70115884e-02, -2.09381487e-02,  4.16513719e-02, -1.36395367e-02,
       -2.28400296e-03,  2.89415792e-02,  2.62450296e-02,  9.43263643e-04,
        2.34983321e-02,  1.90271775e-03,  2.47740541e-02, -1.24531137e-02,
        4.00202051e-02,  3.43703926e-02, -2.26440635e-02,  1.22092254e-02,
       -2.84331888e-02,  4.50385772e-02, -3.06386175e-03, -3.90868150e-02,
       -3.97100188e-02,  1.63540021e-02,  3.36445756e-02, -3.74270050e-04,
       -2.13448629e-02,  4.08029975e-03,  3.59041132e-02,  2.38614772e-02,
        2.67949384e-02,  4.17239517e-02, -3.20797451e-02, -3.43438089e-02,
        1.28215626e-02,  1.81523766e-02, -8.98517203e-03,  3.40453759e-02,
        4.83093411e-02, -1.73787475e-02, -7.43701705e-04, -3.32457833e-02,
        2.86365282e-02,  2.49473117e-02,  1.89821869e-02,  2.27867477e-02,
        9.10710823e-03,  4.33235914e-02, -4.00794409e-02, -1.82732586e-02,
       -1.35323983e-02,  9.21874773e-03, -1.67702790e-02,  7.60652311e-03,
        2.17623338e-02,  5.83713055e-02,  7.57835805e-03,  9.77778062e-03,
       -4.23857495e-02,  3.05826236e-02, -9.97263938e-03,  4.06406224e-02,
        8.58881790e-03, -1.28408773e-02,  9.19344742e-03,  4.02258895e-02,
        2.96371896e-02,  3.50446254e-02,  2.85269525e-02,  4.01970781e-02,
        9.66645591e-03, -2.27576885e-02,  5.81380259e-03,  9.92085971e-03,
       -2.03642379e-02,  1.16815632e-02,  3.33743024e-04,  1.62583627e-02,
        2.19272375e-02,  6.13904791e-03,  2.61194780e-02,  3.42077129e-02,
        2.07219254e-02, -1.75705105e-02,  2.57332250e-03,  1.69954542e-02,
        3.84422205e-02,  3.19246650e-02,  9.09684598e-03,  3.19670737e-02,
        3.65989506e-02,  7.95301422e-02,  9.22384858e-03, -4.48816568e-02,
        2.20393320e-03,  4.05414291e-02, -1.33528877e-02, -7.78291421e-03,
        4.70802747e-02,  2.46529579e-02, -7.95511412e-04, -2.00140495e-02,
        4.04840261e-02,  1.46778254e-02,  2.00576372e-02, -4.08980288e-02,
        5.50644984e-03,  3.00910715e-02,  1.74962450e-02, -1.14184646e-02,
        1.94576848e-02,  3.56941223e-02,  4.29563224e-02, -3.07779363e-03,
        3.64317261e-02, -2.55339220e-03, -9.15231241e-04, -1.27930846e-02,
        3.10072470e-02,  2.55308603e-03, -3.58767323e-02,  4.09958996e-02,
        3.50232162e-02,  1.56846140e-02,  1.49229104e-02, -1.49869341e-02,
        2.42315214e-02,  9.90340021e-03,  2.04353239e-02, -2.92559937e-02,
        1.61311608e-02, -2.33720578e-02, -3.90637554e-02, -1.91179477e-02,
        1.43686216e-02,  2.55368985e-02,  4.01453450e-02, -3.14701907e-02,
        1.74692553e-02,  2.74159457e-03,  6.59541273e-03, -2.99797170e-02,
       -2.70494483e-02, -4.45659086e-03,  1.20872594e-02, -3.13932225e-02,
        3.25472169e-02,  1.70601311e-03, -2.42137723e-02, -1.35724817e-03,
        3.16331089e-02,  2.97153629e-02, -3.19153182e-02,  2.53717843e-02,
       -2.48280820e-02,  1.85750462e-02,  1.31373219e-02, -3.28281634e-02,
        4.08798084e-02, -2.30218507e-02, -6.09474909e-03, -2.36513410e-02,
        2.76976544e-02, -2.45523546e-02, -4.47568670e-02,  3.84247936e-02,
        1.00220758e-02,  2.28480622e-03,  2.48286352e-02,  1.17706927e-02],
      dtype=float32)

In [25]:
print("토이스토리2 : ",np.dot(wooyong_vector, toy_sotry2_vector))

토이스토리2 :  0.9740257

### 오버피팅인가?

In [36]:
wooyong, toy_story = user_to_idx["wooyong"], title_to_idx['toy story (1995)']
wooyong_vector, toy_sotry_vector = als_model.user_factors[wooyong], als_model.item_factors[toy_story]
print("토이스토리1 : ",np.dot(wooyong_vector, toy_sotry_vector))

wooyong, truman = user_to_idx["wooyong"], title_to_idx['truman show, the (1998)']
wooyong_vector, truman_vector = als_model.user_factors[wooyong], als_model.item_factors[truman]
print("트루먼쇼    : ",np.dot(wooyong_vector, truman_vector))

wooyong, aliens = user_to_idx["wooyong"], title_to_idx['aliens (1986)']
wooyong_vector, aliens_vector = als_model.user_factors[wooyong], als_model.item_factors[aliens]
print("에일리언    : ",np.dot(wooyong_vector, aliens_vector))

토이스토리1 :  0.96307224
트루먼쇼    :  0.87785393
에일리언    :  0.9435483

* 좋아하는 영화 리스트로 넣은 영화의 np.dot값을 모두 구한 결과 모두 0.87이상의 값이 나왔다.
 - 이것이 오버피팅인지 아닌지 알 수 없고, 페이지 최하단에 있는 "나에게 추천하는 영화 리스트" 역시 오버피팅에 의한 결과인지는 모르겠다.
 - 하지만 추천시스템의 매력이 이런게 아닌가 싶다

In [27]:
promise = title_to_idx['promise, the (versprechen, das) (1994)']
promise_vector = als_model.item_factors[promise]
np.dot(wooyong_vector, promise_vector)

-0.001130208

In [28]:
favorite_movie = 'toy story 2 (1999)'
movie_id = title_to_idx[favorite_movie]
similar_movie = als_model.similar_items(movie_id, N=15)
similar_movie

[(50, 1.0000001),
 (40, 0.23167254),
 (2137, 0.20654005),
 (1056, 0.19633244),
 (2749, 0.19423422),
 (2144, 0.19248906),
 (2970, 0.1909466),
 (3543, 0.1907865),
 (3453, 0.19062735),
 (1246, 0.19047646),
 (3619, 0.19003619),
 (3201, 0.18925205),
 (1983, 0.18920991),
 (3395, 0.18913202),
 (3437, 0.18908928)]

In [29]:
#artist_to_idx 를 뒤집어, index로부터 artist 이름을 얻는 dict를 생성합니다. 
idx_to_title = {v:k for k,v in title_to_idx.items()}
[idx_to_title[i[0]] for i in similar_movie]

['toy story 2 (1999)',
 'toy story (1995)',
 'tigger movie, the (2000)',
 'vie est belle, la (life is rosey) (1987)',
 'careful (1992)',
 'amityville curse, the (1990)',
 'digimon: the movie (2000)',
 'small wonders (1996)',
 'woo (1998)',
 'homeward bound ii: lost in san francisco (1996)',
 'smoking/no smoking (1993)',
 'allnighter, the (1987)',
 'air bud: golden receiver (1998)',
 'castaway cowboy, the (1974)',
 'assassination (1987)']

## 비슷한 유형의 영화 추천 함수

In [30]:
def get_similar_movie(movie_name: str):
    movie_id = title_to_idx[movie_name]
    similar_movie = als_model.similar_items(movie_id)
    similar_movie = [idx_to_title[i[0]] for i in similar_movie]
    return similar_movie

print("슝=3")

슝=3

In [31]:
get_similar_movie("antz (1998)")

['antz (1998)',
 'perfect blue (1997)',
 'haunted world of edward d. wood jr., the (1995)',
 'meet the deedles (1998)',
 'lassie (1994)',
 "doug's 1st movie (1999)",
 'anna (1996)',
 'celestial clockwork (1994)',
 'buck and the preacher (1972)',
 'mamma roma (1962)']

## 나에게 추천하는 영화

In [32]:
user = user_to_idx['wooyong']
# recommend에서는 user*item CSR Matrix를 받습니다.
movie_recommended = als_model.recommend(user, csr_data, N=20, filter_already_liked_items=True)
movie_recommended

[(428, 0.0321986),
 (1725, 0.029286575),
 (481, 0.028376864),
 (516, 0.027806532),
 (2200, 0.027507983),
 (1646, 0.026931664),
 (1348, 0.026586518),
 (2054, 0.026404718),
 (2227, 0.02631785),
 (491, 0.026263997),
 (374, 0.026193928),
 (982, 0.025991287),
 (1182, 0.025893766),
 (605, 0.025450805),
 (2290, 0.025352744),
 (1861, 0.025163032),
 (1496, 0.02489403),
 (2126, 0.024768522),
 (1329, 0.024635559),
 (1701, 0.024416953)]

In [33]:
[idx_to_title[i[0]] for i in movie_recommended]

['alive (1993)',
 'beach, the (2000)',
 'kolya (1996)',
 'sabrina (1995)',
 'bottle rocket (1996)',
 'yellow submarine (1968)',
 'creature comforts (1990)',
 'bad boys (1995)',
 'end of the affair, the (1999)',
 'bronx tale, a (1993)',
 'exorcist, the (1973)',
 'in the name of the father (1993)',
 'red dawn (1984)',
 'cool runnings (1993)',
 'ninth gate, the (2000)',
 'pawnbroker, the (1965)',
 'peacemaker, the (1997)',
 'rounders (1998)',
 'modern times (1936)',
 'my own private idaho (1991)']

# 고찰
- csr 매트리스에 대한 개념이해가 어려웠을 뿐, 흥미로운 주제였다.
- 왜 0.97이 나왔는데 추천영화는 마음에 안드는 영화 투성인지 모르겟다
- 추천시스템의 맹점인지 epoch수를 줄여서 0.25가 나올때는 제법 마음에드는 영화가 많았다.
- [정답은 이거다!] 라는게 없으니 애매한 분야인 것 같다.